const GOOGLE_REVIEW_URL="https://www.google.com/maps/place/Rajashree+Foods+(Heritage+Handmades)/@18.4405805,73.8135441,17z/data=!4m8!3m7!1s0x3bc295e4a684dba7:0xac5e074ef58ae1!8m2!3d18.4405805!4d73.8135441!9m1!1b1!16s%2Fg%2F11yjg48m3l?entry=ttu&g_ep=EgoyMDI2MDcwOC4wIKXMDSoASAFQAw%3D%3D";
let tasteRating=5,qualityRating=5,lastData=null;
const $=id=>document.getElementById(id);
const pick=a=>a[Math.floor(Math.random()*a.length)];
function buildStars(id,cb){const c=$(id);c.innerHTML="";for(let i=1;i<=5;i++){const s=document.createElement("span");s.textContent="★";s.className="star on";s.title=i+" star";s.onclick=()=>{[...c.children].forEach((x,n)=>x.classList.toggle("on",n<i));cb(i)};c.appendChild(s)}}
buildStars("tasteStars",v=>tasteRating=v);buildStars("qualityStars",v=>qualityRating=v);
function settings(){return{endpoint:localStorage.getItem("rajshree_api_endpoint")||"",model:localStorage.getItem("rajshree_api_model")||"gpt-4o-mini",key:localStorage.getItem("rajshree_api_key")||""}}
function updateAIStatus(){const s=settings();$("aiStatus").textContent=s.endpoint&&s.key?"AI Mode: Real AI API enabled":"AI Mode: Human-style smart generator"}
function clean(v){return (v||"").trim().replace(/\s+/g," ")}
function inputs(){return{language:$("language").value,productType:$("productType").value,tone:$("tone").value,length:$("length").value,likedMost:clean($("likedMost").value),specialMention:clean($("specialMention").value),tasteRating,qualityRating}}
function productLine(p){if(p.includes("Chakli"))return pick(["We tried Rajshree Foods' bhajani chakli recently.","I ordered bhajani chakli from Rajshree Foods and it had a nice homemade feel.","Rajshree Foods' chakli reminded us of traditional festive snacks at home."]);if(p.includes("Karanji"))return pick(["We tried the karanji from Rajshree Foods.","The karanji from Rajshree Foods had a nice traditional taste."]);if(p.includes("Ladoo"))return pick([`We ordered ${p.toLowerCase()} from Rajshree Foods.`,`The ${p.toLowerCase()} from Rajshree Foods tasted fresh and homemade.`]);if(p.includes("Chivda"))return pick(["We tried pohe chivda from Rajshree Foods.","The chivda from Rajshree Foods was fresh and nicely balanced in taste."]);if(p.includes("Puranpoli"))return pick(["We ordered puranpoli from Rajshree Foods.","The puranpoli had a traditional homemade taste."]);return pick([`We tried ${p.toLowerCase()} from Rajshree Foods.`,`Recently ordered snacks and sweets from Rajshree Foods.`,`We ordered from Rajshree Foods for a family occasion.`])}
function tasteLine(r){if(r>=5)return pick(["The taste was authentic, fresh, and very satisfying.","The flavour felt homemade and everyone enjoyed it.","The taste was excellent and had a proper traditional touch."]);if(r===4)return pick(["The taste was good overall and quite enjoyable.","The flavour was nice, with only small scope for improvement."]);if(r===3)return pick(["The taste was decent, though a few things could be improved.","Overall taste was satisfactory, with some items better than others."]);return pick(["The taste was okay, but there is room for improvement.","Some parts were fine, but the taste can be improved next time."])}
function qualityLine(r){if(r>=5)return pick(["Quality and freshness were clearly maintained.","The preparation felt hygienic, fresh, and carefully packed.","Freshness and quality were very good."]);if(r===4)return pick(["Quality was good and packaging was neat.","Freshness was good overall and the item was packed properly."]);if(r===3)return pick(["Quality was acceptable, though it can be improved slightly.","Packaging and freshness were satisfactory overall."]);return pick(["Quality can be improved in a few areas.","Packaging and freshness need some improvement."])}
function highlightLine(d){let arr=[];if(d.likedMost)arr.push(pick([`I especially liked ${d.likedMost}.`,`What stood out was ${d.likedMost}.`,`A good part of the order was ${d.likedMost}.`]));if(d.specialMention)arr.push(pick([`${d.specialMention} was also worth mentioning.`,`A special mention for ${d.specialMention}.`,`The ${d.specialMention} made the order feel more special.`]));return arr.join(" ")}
function closeLine(d){const good=d.tasteRating>=4&&d.qualityRating>=4;if(good)return pick(["Overall, a good place for traditional homemade snacks and sweets.","Would definitely consider ordering again for family functions and festivals.","Happy with the experience and would recommend Rajshree Foods to others."]);return pick(["Overall, it was a decent experience, and with a few improvements it can become better.","I appreciate the effort and hope the small improvement areas are considered positively.","The experience was satisfactory, with some good parts and some scope for improvement."])}
function englishReview(d){let pieces=[productLine(d.productType),tasteLine(d.tasteRating),qualityLine(d.qualityRating),highlightLine(d),closeLine(d)].filter(Boolean);let review=pieces.join(" ");if(d.tone==="Short & Simple"||d.length==="Short")review=pieces.slice(0,3).join(" ")+" "+closeLine(d);if(d.tone==="Traditional & Family Style"&&d.tasteRating>=4)review += " It gives a nice feeling of homemade festive food.";if(d.tone==="Emotional & Festive"&&d.tasteRating>=4)review += " It made the occasion feel more special.";if(d.length==="Detailed")review += " The review is based on the taste, freshness, packaging, and overall ordering experience.";return review.replace(/\s+/g," ").trim()}
function localReview(d){if(d.language==="English")return englishReview(d);const good=d.tasteRating>=4&&d.qualityRating>=4;if(d.language==="Hindi")return `हमने Rajshree Foods से ${d.productType} लिया। स्वाद अच्छा और घर जैसा लगा। ताजगी और quality भी अच्छी रही।${d.likedMost?` हमें खास तौर पर ${d.likedMost} पसंद आया।`:""}${d.specialMention?` ${d.specialMention} भी अच्छा रहा।`:""} ${good?"कुल मिलाकर पारंपरिक snacks और sweets के लिए अच्छा अनुभव रहा।":"कुल मिलाकर अनुभव ठीक रहा, कुछ सुधार की गुंजाइश है।"}`;if(d.language==="Marathi")return `आम्ही Rajshree Foods कडून ${d.productType} घेतले. चव चांगली आणि घरगुती वाटली. Freshness आणि quality देखील चांगली होती.${d.likedMost?` आम्हाला विशेषतः ${d.likedMost} आवडले.`:""}${d.specialMention?` ${d.specialMention} विशेष उल्लेखनीय होते.`:""} ${good?"एकूण पारंपरिक snacks आणि sweets साठी चांगला अनुभव होता.":"एकूण अनुभव ठीक होता, काही सुधारणा केल्या तर अजून चांगले होईल."}`;if(d.language==="Gujarati")return `અમે Rajshree Foods માંથી ${d.productType} લીધું. સ્વાદ સારો અને ઘરગથ્થુ લાગ્યો. Freshness અને quality પણ સારી હતી.${d.likedMost?` અમને ખાસ કરીને ${d.likedMost} ગમ્યું.`:""}${d.specialMention?` ${d.specialMention} પણ સારું રહ્યું.`:""} ${good?"કુલ મળીને traditional snacks અને sweets માટે સારો અનુભવ રહ્યો.":"કુલ અનુભવ ઠીક રહ્યો, થોડા સુધારા માટે જગ્યા છે."}`;return englishReview(d)}
async function callAI(d,instruction=""){const s=settings();if(!s.endpoint||!s.key)return null;const prompt=`Write one natural first-person Google review for Rajshree Foods, a homemade Indian snacks and sweets brand. It must sound like a real customer wrote it. Product:${d.productType}. Language:${d.language}. Tone:${d.tone}. Length:${d.length}. Taste rating:${d.tasteRating}/5. Freshness/quality rating:${d.qualityRating}/5. Customer liked:${d.likedMost||"not specified"}. Special mention:${d.specialMention||"not specified"}. Extra instruction:${instruction||"none"}. If ratings are below 4, write balanced polite feedback. Output only the review text.`;const res=await fetch(s.endpoint,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${s.key}`},body:JSON.stringify({model:s.model,messages:[{role:"system",content:"You write authentic first-person customer reviews."},{role:"user",content:prompt}],temperature:.9,presence_penalty:.4,frequency_penalty:.4})});if(!res.ok)throw new Error("AI API error "+res.status);const j=await res.json();return j.choices?.[0]?.message?.content?.trim()||null}
async function generate(instruction="",useLast=false){const d=useLast&&lastData?lastData:inputs();lastData=d;let r=null;try{r=await callAI(d,instruction)}catch(e){console.warn(e)}if(!r)r=localReview(d);$("reviewOutput").value=r;$("formScreen").classList.add("hidden");$("resultScreen").classList.remove("hidden")}
function copyReview(){const o=$("reviewOutput");o.select();navigator.clipboard.writeText(o.value);alert("Review copied successfully!")}
function openSettings(){const s=settings();$("apiEndpoint").value=s.endpoint;$("apiModel").value=s.model;$("apiKey").value=s.key;$("settingsDialog").showModal()}
function saveSettings(e){e.preventDefault();localStorage.setItem("rajshree_api_endpoint",$("apiEndpoint").value.trim());localStorage.setItem("rajshree_api_model",$("apiModel").value.trim()||"gpt-4o-mini");localStorage.setItem("rajshree_api_key",$("apiKey").value.trim());$("settingsDialog").close();updateAIStatus()}
$("generateBtn").onclick=()=>generate();$("freshBtn").onclick=()=>generate("",true);$("rewriteBtn").onclick=()=>generate($("customInstruction").value.trim(),true);$("copyBtn").onclick=copyReview;$("googleBtn").onclick=()=>window.open(GOOGLE_REVIEW_URL,"_blank","noopener,noreferrer");$("againBtn").onclick=()=>{$("resultScreen").classList.add("hidden");$("formScreen").classList.remove("hidden")};$("apiSettingsBtn").onclick=openSettings;$("saveSettingsBtn").onclick=saveSettings;updateAIStatus();
